export default {
  "login": "dev-csa",
  "id": 29699395,
  "node_id": "MDQ6VXNlcjI5Njk5Mzk1",
  "avatar_url": "https://avatars.githubusercontent.com/u/29699395?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/dev-csa",
  "html_url": "https://github.com/dev-csa",
  "followers_url": "https://api.github.com/users/dev-csa/followers",
  "following_url": "https://api.github.com/users/dev-csa/following{/other_user}",
  "gists_url": "https://api.github.com/users/dev-csa/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/dev-csa/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/dev-csa/subscriptions",
  "organizations_url": "https://api.github.com/users/dev-csa/orgs",
  "repos_url": "https://api.github.com/users/dev-csa/repos",
  "events_url": "https://api.github.com/users/dev-csa/events{/privacy}",
  "received_events_url": "https://api.github.com/users/dev-csa/received_events",
  "type": "User",
  "site_admin": false,
  "name": "뎁csa",
  "company": "Nielsen",
  "blog": "",
  "location": "Seoul, Korea",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 21,
  "public_gists": 0,
  "followers": 1,
  "following": 1,
  "created_at": "2017-06-26T04:37:05Z",
  "updated_at": "2021-04-28T02:16:55Z"
};
